# Generated by Django 4.0.3 on 2022-04-22 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xpay', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='email',
        ),
    ]
